stages:
  - compile angular
  - build image
  - run container

compile:
  stage: compile angular
  image: trion/ng-cli
  before_script:
    - cd frontend4cash
    - npm i
    - npm ci
  script:
    - ng build --prod --verbose=true

build:
  stage: build image
  before_script:
        - source .${CI_COMMIT_REF_NAME}.env
  script:
        - echo ${IMAGE_NAME}
        - echo "actually echoed IMAGE NAME"
        - docker build -t ${IMAGE_NAME} .

deploy:
  stage: run container
  before_script:
          - source .${CI_COMMIT_REF_NAME}.env
  script: docker container run -d --name $APP_NAME - p $PORT:80 ${IMAGE_NAME}
