stages:
  - pull the code
  - compile angular
  - build image
  - run container

pull:
  stage: pull the code
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
  script:
    - git pull git@gitlab.cs.ttu.ee:kigris/frontend4cash.git

compile:
  stage: compile angular
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
    - npm i
    - npm ci
  script:
    - ng build --prod --verbose=true

build:
  stage: build image
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
    - source .${CI_COMMIT_REF_NAME}.env
  script: docker build -t $IMAGE_NAME .

deploy:
  stage: run container
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
    - source .${CI_COMMIT_REF_NAME}.env
    - docker stop $APP_NAME
    - docker container rm $APP_NAME
  script: docker container run -d --name $APP_NAME - p $PORT:80 $IMAGE_NAME
# i am a comment
