stages:
  - pull the code
  - compile angular
  - build image
  - stop running container
  - run container

pull:
  stage: pull the code
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
  script:
    - git pull git@gitlab.cs.ttu.ee:kigris/frontend4cash.git

compile:
  stage: compile angular
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
    - npm i
    - npm ci
  script:
    - ng build --prod --verbose=true

build:
  stage: build image
  before_script:
    - cd /home/ubuntu/bits4cash/frontend4cash
    - source .${CI_COMMIT_REF_NAME}.env
  script: docker build -t $IMAGE_NAME .

stop:
  stage: stop running container
  allow_failure: true
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
  script:
    - docker stop $APP_NAME
    - docker container rm $APP_NAME

deploy:
  stage: run container
  before_script:
    # no need to cd but let it be here for a while
    - cd /home/ubuntu/bits4cash/frontend4cash
    - source .${CI_COMMIT_REF_NAME}.env
  script: docker container run -d --name $APP_NAME --net=$NETWORK_NAME --net-alias=$APP_NAME -p $PORT:80 $IMAGE_NAME
# i am a comment for test
